import { AX, DATA } from "@/data";
import { KpiRow, TrendChart, BarH, GroupBar, Donut, DonutLegend, ChartCard, Grid2, TableCard, num } from "@/components/charts";
import { A, money, scale } from "@/lib/format";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";

const pick = (kpis: any[], labels: string[]) => kpis.filter((k) => labels.includes(k.l));
function Tl({ tabs }: { tabs: string[] }) {
  return <TabsList>{tabs.map((t) => <TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList>;
}

/* ================= Google Ads ================= */
export function GoogleAdsView({ d, f }: { d: any; f: number }) {
  const trend = <TrendChart labels={AX} series={[{ name: "Cost", data: A(d.trend.cost, f) }, { name: "Conv.", data: A(d.trend.conv, f) }]} dual />;
  // Clicks per device = total clicks × device share; scales with the date range so the card responds.
  const devClicks = d.devices.data.map((s: number) => Math.round(((d.base?.clicks ?? 0) * s) / 100));
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Performance", "Campaigns", "Keywords", "Devices"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Cost & Conversions" legend={["Cost", "Conv."]}>{trend}</ChartCard><ChartCard title="Clicks by device"><Donut labels={d.devices.labels} data={A(devClicks, f)} /><DonutLegend labels={d.devices.labels} data={A(devClicks, f)} count /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Performance" className="space-y-4"><ChartCard title="Cost & Conversions" legend={["Cost", "Conv."]}><TrendChart labels={AX} series={[{ name: "Cost", data: A(d.trend.cost, f) }, { name: "Conv.", data: A(d.trend.conv, f) }]} dual height={320} /></ChartCard><ChartCard title="Cost by campaign"><BarH labels={d.campaigns.map((x: any) => x.name)} data={A(d.campaigns.map((x: any) => x.cost), f)} /></ChartCard></TabsContent>
      <TabsContent value="Campaigns"><TableCard title="Campaign performance"><Table><TableHeader><TableRow><TableHead>Campaign</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Cost</TableHead><TableHead className="text-right">Clicks</TableHead><TableHead className="text-right">Conv.</TableHead><TableHead className="text-right">CPA</TableHead><TableHead className="text-right">ROAS</TableHead></TableRow></TableHeader><TableBody>{d.campaigns.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.name}</TableCell><TableCell><Badge variant={x.status === "on" ? "success" : "warning"}>{x.status === "on" ? "Active" : "Paused"}</Badge></TableCell><TableCell className={num()}>{money(scale(x.cost, f))}</TableCell><TableCell className={num()}>{scale(x.clicks, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>{scale(x.conv, f)}</TableCell><TableCell className={num()}>${x.cpa}</TableCell><TableCell className={num()}>{x.roas}x</TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
      <TabsContent value="Keywords" className="space-y-4"><TableCard title="Top keywords"><Table><TableHeader><TableRow><TableHead>Keyword</TableHead><TableHead className="text-right">Clicks</TableHead><TableHead className="text-right">CPC</TableHead><TableHead className="text-right">Conv.</TableHead><TableHead>Quality</TableHead></TableRow></TableHeader><TableBody>{d.keywords.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.kw}</TableCell><TableCell className={num()}>{scale(x.clicks, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>${x.cpc.toFixed(2)}</TableCell><TableCell className={num()}>{scale(x.conv, f)}</TableCell><TableCell><Badge variant={x.qs >= 8 ? "success" : x.qs >= 6 ? "warning" : "muted"}>{x.qs}/10</Badge></TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Clicks by keyword"><BarH labels={d.keywords.map((x: any) => x.kw)} data={A(d.keywords.map((x: any) => x.clicks), f)} /></ChartCard></TabsContent>
      <TabsContent value="Devices"><Grid2><ChartCard title="Clicks by device"><Donut labels={d.devices.labels} data={A(devClicks, f)} /><DonutLegend labels={d.devices.labels} data={A(devClicks, f)} count /></ChartCard><TableCard title="Breakdown"><Table><TableHeader><TableRow><TableHead>Device</TableHead><TableHead className="text-right">Share</TableHead></TableRow></TableHeader><TableBody>{d.devices.labels.map((l: string, i: number) => <TableRow key={i}><TableCell className="font-medium">{l}</TableCell><TableCell className={num()}>{d.devices.data[i]}%</TableCell></TableRow>)}</TableBody></Table></TableCard></Grid2></TabsContent>
    </Tabs>
  );
}

/* ================= Facebook Page / Instagram (shared shape) ================= */
function SocialOrganic({ d, f }: { d: any; f: number }) {
  const growth = <TrendChart labels={AX} series={[{ name: "Net new", data: A(d.growth.net, f) }, { name: "Total", data: A(d.growth.cum, f) }]} dual />;
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Growth", "Engagement", "Top Posts", "Demographics"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Follower growth" legend={["Net new", "Total"]}>{growth}</ChartCard><ChartCard title="Reach & Impressions" legend={["Reach", "Impr."]}><TrendChart labels={AX} series={[{ name: "Reach", data: A(d.reach.reach, f) }, { name: "Impr.", data: A(d.reach.impr, f) }]} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Growth" className="space-y-4"><ChartCard title="Follower growth" legend={["Net new", "Total"]}><TrendChart labels={AX} series={[{ name: "Net new", data: A(d.growth.net, f) }, { name: "Total", data: A(d.growth.cum, f) }]} dual height={320} /></ChartCard><ChartCard title="Net new per period"><GroupBar labels={AX} groups={[{ name: "Net new", data: A(d.growth.net, f) }]} /></ChartCard></TabsContent>
      <TabsContent value="Engagement"><Grid2><ChartCard title="Engagement by type"><Donut labels={d.engType.labels} data={A(d.engType.data, f)} /><DonutLegend labels={d.engType.labels} data={A(d.engType.data, f)} /></ChartCard><ChartCard title="Reach per post"><GroupBar labels={AX} groups={[{ name: "Reach", data: A(d.postReach, f) }]} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Top Posts"><TableCard title="Top posts"><Table><TableHeader><TableRow><TableHead>Post</TableHead><TableHead>Published</TableHead><TableHead className="text-right">Reach</TableHead><TableHead className="text-right">Engagements</TableHead><TableHead className="text-right">Eng. Rate</TableHead></TableRow></TableHeader><TableBody>{d.posts.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.post}</TableCell><TableCell className="text-muted-foreground">{x.date}</TableCell><TableCell className={num()}>{scale(x.reach, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>{scale(x.eng, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>{x.rate}%</TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
      <TabsContent value="Demographics"><ChartCard title="Audience by age & gender" legend={["Women", "Men"]}><GroupBar labels={d.demo.labels} groups={[{ name: "Women", data: d.demo.women }, { name: "Men", data: d.demo.men }]} /></ChartCard></TabsContent>
    </Tabs>
  );
}
export function FbPageView(p: { d: any; f: number }) { return <SocialOrganic {...p} />; }
export function IgView(p: { d: any; f: number }) { return <SocialOrganic {...p} />; }

/* ================= LinkedIn ================= */
export function LinkedInView({ d, f }: { d: any; f: number }) {
  const trend = <TrendChart labels={AX} series={[{ name: "Impressions", data: A(d.trend.impr, f) }, { name: "Engagements", data: A(d.trend.eng, f) }]} dual />;
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Performance", "Audience", "Top Posts"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Impressions & engagement" legend={["Impressions", "Engagements"]}>{trend}</ChartCard><ChartCard title="Audience by seniority"><Donut labels={d.seniority.labels} data={d.seniority.data} /><DonutLegend labels={d.seniority.labels} data={d.seniority.data} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Performance"><ChartCard title="Impressions & engagement" legend={["Impressions", "Engagements"]}><TrendChart labels={AX} series={[{ name: "Impressions", data: A(d.trend.impr, f) }, { name: "Engagements", data: A(d.trend.eng, f) }]} dual height={320} /></ChartCard></TabsContent>
      <TabsContent value="Audience"><Grid2><ChartCard title="By seniority"><Donut labels={d.seniority.labels} data={d.seniority.data} /><DonutLegend labels={d.seniority.labels} data={d.seniority.data} /></ChartCard><ChartCard title="By industry"><Donut labels={d.industry.labels} data={d.industry.data} /><DonutLegend labels={d.industry.labels} data={d.industry.data} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Top Posts"><TableCard title="Top posts"><Table><TableHeader><TableRow><TableHead>Post</TableHead><TableHead>Published</TableHead><TableHead className="text-right">Impr.</TableHead><TableHead className="text-right">Engagements</TableHead><TableHead className="text-right">Eng. Rate</TableHead></TableRow></TableHeader><TableBody>{d.posts.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.post}</TableCell><TableCell className="text-muted-foreground">{x.date}</TableCell><TableCell className={num()}>{scale(x.impr, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>{scale(x.eng, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>{x.rate}%</TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
    </Tabs>
  );
}

/* ================= Web Analytics (GA4) ================= */
export function Ga4View({ d, f }: { d: any; f: number }) {
  // Sessions per device = total sessions × device share; scales with the date range.
  const devSessions = d.devices.data.map((s: number) => Math.round(((d.base?.sessions ?? 0) * s) / 100));
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Acquisition", "Behaviour", "Audience", "Conversions"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Users over time" legend={["New", "Returning"]}><TrendChart labels={AX} series={[{ name: "New", data: A(d.users.nw, f) }, { name: "Returning", data: A(d.users.ret, f) }]} /></ChartCard><ChartCard title="Sessions by device"><Donut labels={d.devices.labels} data={A(devSessions, f)} /><DonutLegend labels={d.devices.labels} data={A(devSessions, f)} count /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Acquisition" className="space-y-4"><TableCard title="Acquisition channels"><Table><TableHeader><TableRow><TableHead>Channel</TableHead><TableHead className="text-right">Sessions</TableHead><TableHead className="text-right">Conv. Rate</TableHead><TableHead className="text-right">Revenue</TableHead></TableRow></TableHeader><TableBody>{d.channels.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.ch}</TableCell><TableCell className={num()}>{scale(x.sess, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>{x.cr}%</TableCell><TableCell className={num()}>{money(scale(x.rev, f))}</TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Sessions by channel"><BarH labels={d.channels.map((x: any) => x.ch)} data={A(d.channels.map((x: any) => x.sess), f)} /></ChartCard></TabsContent>
      <TabsContent value="Behaviour" className="space-y-4"><TableCard title="Top pages"><Table><TableHeader><TableRow><TableHead>Page</TableHead><TableHead className="text-right">Views</TableHead><TableHead className="text-right">Avg. Time</TableHead><TableHead className="text-right">Bounce</TableHead></TableRow></TableHeader><TableBody>{d.pages.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.p}</TableCell><TableCell className={num()}>{scale(x.views, f).toLocaleString("en-AU")}</TableCell><TableCell className={num()}>{x.time}s</TableCell><TableCell className={num()}>{x.bounce}%</TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Page views"><BarH labels={d.pages.map((x: any) => x.p)} data={A(d.pages.map((x: any) => x.views), f)} /></ChartCard></TabsContent>
      <TabsContent value="Audience"><Grid2><ChartCard title="Sessions by device"><Donut labels={d.devices.labels} data={A(devSessions, f)} /><DonutLegend labels={d.devices.labels} data={A(devSessions, f)} count /></ChartCard><TableCard title="Top countries"><Table><TableHeader><TableRow><TableHead>Country</TableHead><TableHead className="text-right">Sessions</TableHead></TableRow></TableHeader><TableBody>{d.geo.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.c}</TableCell><TableCell className={num()}>{scale(x.sess, f).toLocaleString("en-AU")}</TableCell></TableRow>)}</TableBody></Table></TableCard></Grid2></TabsContent>
      <TabsContent value="Conversions"><Grid2><ChartCard title="Conversion funnel"><BarH labels={d.funnel.map((x: any) => x.s)} data={A(d.funnel.map((x: any) => x.v), f)} /></ChartCard><TableCard title="Funnel steps"><Table><TableHeader><TableRow><TableHead>Step</TableHead><TableHead className="text-right">Users</TableHead></TableRow></TableHeader><TableBody>{d.funnel.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.s}</TableCell><TableCell className={num()}>{scale(x.v, f).toLocaleString("en-AU")}</TableCell></TableRow>)}</TableBody></Table></TableCard></Grid2></TabsContent>
    </Tabs>
  );
}

/* ================= Call Tracking ================= */
export function CallTrackingView({ d, f }: { d: any; f: number }) {
  const tierBadge = (t: string) => (t === "Hot lead" ? "success" : t === "Spam" ? "warning" : "muted") as any;
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Call Volume", "Sources", "Conversation Intel"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Answered vs missed" legend={["Answered", "Missed"]}><TrendChart labels={AX} series={[{ name: "Answered", data: A(d.trend.answered, f) }, { name: "Missed", data: A(d.trend.missed, f) }]} /></ChartCard><ChartCard title="Calls by source"><Donut labels={d.sources.map((x: any) => x.src)} data={A(d.sources.map((x: any) => x.calls), f)} /><DonutLegend labels={d.sources.map((x: any) => x.src)} data={A(d.sources.map((x: any) => x.calls), f)} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Call Volume" className="space-y-4"><ChartCard title="Calls by day of week" legend={["Answered", "Missed"]}><GroupBar labels={d.byday.labels} groups={[{ name: "Answered", data: A(d.byday.answered, f) }, { name: "Missed", data: A(d.byday.missed, f) }]} /></ChartCard><ChartCard title="Calls over time" legend={["Answered", "Missed"]}><TrendChart labels={AX} series={[{ name: "Answered", data: A(d.trend.answered, f) }, { name: "Missed", data: A(d.trend.missed, f) }]} /></ChartCard></TabsContent>
      <TabsContent value="Sources" className="space-y-4"><TableCard title="Calls by source"><Table><TableHeader><TableRow><TableHead>Source</TableHead><TableHead className="text-right">Calls</TableHead><TableHead className="text-right">Answered</TableHead><TableHead className="text-right">Qualified</TableHead><TableHead className="text-right">Cost / Call</TableHead></TableRow></TableHeader><TableBody>{d.sources.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.src}</TableCell><TableCell className={num()}>{scale(x.calls, f)}</TableCell><TableCell className={num()}>{scale(x.ans, f)}</TableCell><TableCell className={num()}>{scale(x.qual, f)}</TableCell><TableCell className={num()}>{x.cpc ? "$" + x.cpc.toFixed(2) : "—"}</TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Calls by source"><BarH labels={d.sources.map((x: any) => x.src)} data={A(d.sources.map((x: any) => x.calls), f)} /></ChartCard></TabsContent>
      <TabsContent value="Conversation Intel" className="space-y-4"><Grid2><ChartCard title="Call quality tiers"><Donut labels={d.tiers.labels} data={A(d.tiers.data, f)} /><DonutLegend labels={d.tiers.labels} data={A(d.tiers.data, f)} /></ChartCard><TableCard title="Keywords driving calls"><Table><TableHeader><TableRow><TableHead>Keyword</TableHead><TableHead className="text-right">Calls</TableHead></TableRow></TableHeader><TableBody>{d.keywords.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.kw}</TableCell><TableCell className={num()}>{scale(x.calls, f)}</TableCell></TableRow>)}</TableBody></Table></TableCard></Grid2><TableCard title="Recent calls"><Table><TableHeader><TableRow><TableHead>Caller</TableHead><TableHead>Source</TableHead><TableHead className="text-right">Duration</TableHead><TableHead>Outcome</TableHead><TableHead>Sentiment</TableHead><TableHead>Tier</TableHead></TableRow></TableHeader><TableBody>{d.recent.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.caller}</TableCell><TableCell className="text-muted-foreground">{x.src}</TableCell><TableCell className={num()}>{x.dur}</TableCell><TableCell><Badge variant={x.outcome === "Booked" ? "success" : x.outcome === "Spam" ? "warning" : "muted"}>{x.outcome}</Badge></TableCell><TableCell>{x.sent}</TableCell><TableCell><Badge variant={tierBadge(x.tier)}>{x.tier}</Badge></TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
    </Tabs>
  );
}

/* ================= Pipeline (CRM) ================= */
export function PipelineView({ d, f }: { d: any; f: number }) {
  const wl = <TrendChart labels={AX} series={[{ name: "Won", data: A(d.wonlost.won, f) }, { name: "Lost", data: A(d.wonlost.lost, f) }]} />;
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Pipeline Stages", "Won & Lost", "Source Attribution"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Pipeline value by stage"><BarH labels={d.stages.map((x: any) => x.stage)} data={A(d.stages.map((x: any) => x.value), f)} /></ChartCard><ChartCard title="Deals won vs lost" legend={["Won", "Lost"]}>{wl}</ChartCard></Grid2></TabsContent>
      <TabsContent value="Pipeline Stages"><Grid2><ChartCard title="Value by stage"><BarH labels={d.stages.map((x: any) => x.stage)} data={A(d.stages.map((x: any) => x.value), f)} /></ChartCard><TableCard title="Stages"><Table><TableHeader><TableRow><TableHead>Stage</TableHead><TableHead className="text-right">Deals</TableHead><TableHead className="text-right">Value</TableHead></TableRow></TableHeader><TableBody>{d.stages.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.stage}</TableCell><TableCell className={num()}>{scale(x.count, f)}</TableCell><TableCell className={num()}>{money(scale(x.value, f))}</TableCell></TableRow>)}</TableBody></Table></TableCard></Grid2></TabsContent>
      <TabsContent value="Won & Lost" className="space-y-4"><ChartCard title="Deals won vs lost" legend={["Won", "Lost"]}><TrendChart labels={AX} series={[{ name: "Won", data: A(d.wonlost.won, f) }, { name: "Lost", data: A(d.wonlost.lost, f) }]} height={300} /></ChartCard><TableCard title="Open deals"><Table><TableHeader><TableRow><TableHead>Company</TableHead><TableHead>Source</TableHead><TableHead>Stage</TableHead><TableHead className="text-right">Value</TableHead><TableHead className="text-right">Age</TableHead></TableRow></TableHeader><TableBody>{d.deals.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.co}</TableCell><TableCell className="text-muted-foreground">{x.src}</TableCell><TableCell><Badge variant="muted">{x.stage}</Badge></TableCell><TableCell className={num()}>{money(scale(x.value, f))}</TableCell><TableCell className={num()}>{x.age}d</TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
      <TabsContent value="Source Attribution" className="space-y-4"><TableCard title="Opportunities by ad source — UTM → pipeline"><Table><TableHeader><TableRow><TableHead>Source</TableHead><TableHead className="text-right">Opps</TableHead><TableHead className="text-right">Won</TableHead><TableHead className="text-right">Value</TableHead><TableHead className="text-right">CAC</TableHead></TableRow></TableHeader><TableBody>{d.bysource.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.src}</TableCell><TableCell className={num()}>{scale(x.opps, f)}</TableCell><TableCell className={num()}>{scale(x.won, f)}</TableCell><TableCell className={num()}>{money(scale(x.value, f))}</TableCell><TableCell className={num()}>{x.cac ? money(x.cac) : "—"}</TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Pipeline value by source"><BarH labels={d.bysource.map((x: any) => x.src)} data={A(d.bysource.map((x: any) => x.value), f)} /></ChartCard></TabsContent>
    </Tabs>
  );
}

/* ================= Speed-to-Lead ================= */
export function SpeedToLeadView({ d, f }: { d: any; f: number }) {
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Response Time", "By Source", "Impact"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Response time distribution"><GroupBar labels={d.dist.labels} groups={[{ name: "Leads", data: A(d.dist.data, f) }]} /></ChartCard><ChartCard title="Avg. response over time (min)"><TrendChart labels={AX} series={[{ name: "Avg min", data: d.trend.avg }]} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Response Time" className="space-y-4"><ChartCard title="Distribution of first response"><GroupBar labels={d.dist.labels} groups={[{ name: "Leads", data: A(d.dist.data, f) }]} /></ChartCard><ChartCard title="Average response over time (min)"><TrendChart labels={AX} series={[{ name: "Avg min", data: d.trend.avg }]} /></ChartCard></TabsContent>
      <TabsContent value="By Source" className="space-y-4"><TableCard title="Response by source"><Table><TableHeader><TableRow><TableHead>Source</TableHead><TableHead className="text-right">Avg. Response</TableHead><TableHead className="text-right">% Under 5 min</TableHead><TableHead className="text-right">Booking Rate</TableHead></TableRow></TableHeader><TableBody>{d.bysource.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.src}</TableCell><TableCell className={num()}>{x.avg}m</TableCell><TableCell className={num()}>{x.under5}%</TableCell><TableCell className={num()}>{x.book}%</TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Avg. response by source (min)"><BarH labels={d.bysource.map((x: any) => x.src)} data={d.bysource.map((x: any) => x.avg)} /></ChartCard></TabsContent>
      <TabsContent value="Impact" className="space-y-4"><ChartCard title="Booking rate by response time" desc="Faster response = more bookings"><GroupBar labels={d.impact.labels} groups={[{ name: "Booking %", data: d.impact.book }]} /></ChartCard><Card><CardHeader className="pb-2"><CardTitle className="text-[15px]">Why it matters</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><div className="flex gap-2"><span className="text-primary">›</span><span>Leads contacted <b>under 5 minutes</b> book at <b>{d.impact.book[0]}%</b> — vs just <b>{d.impact.book[d.impact.book.length - 1]}%</b> after 24 hours.</span></div><div className="flex gap-2"><span className="text-primary">›</span><span>Average response improved from <b>{d.trend.avg[0]}m</b> to <b>{d.trend.avg[d.trend.avg.length - 1]}m</b> this period.</span></div></CardContent></Card></TabsContent>
    </Tabs>
  );
}

/* ================= Show-Rate ================= */
export function ShowRateView({ d, f }: { d: any; f: number }) {
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Trend", "By Source", "No-show Reasons"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Show rate over time (%)"><TrendChart labels={AX} series={[{ name: "Show rate", data: d.trend.show }]} /></ChartCard><ChartCard title="No-show reasons"><Donut labels={d.reasons.labels} data={A(d.reasons.data, f)} /><DonutLegend labels={d.reasons.labels} data={A(d.reasons.data, f)} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Trend" className="space-y-4"><ChartCard title="Show rate (%)"><TrendChart labels={AX} series={[{ name: "Show rate", data: d.trend.show }]} height={320} /></ChartCard><ChartCard title="Show rate by source (%)"><BarH labels={d.bysource.map((x: any) => x.src)} data={d.bysource.map((x: any) => x.rate)} /></ChartCard></TabsContent>
      <TabsContent value="By Source" className="space-y-4"><TableCard title="Show rate by source"><Table><TableHeader><TableRow><TableHead>Source</TableHead><TableHead className="text-right">Booked</TableHead><TableHead className="text-right">Showed</TableHead><TableHead className="text-right">Show Rate</TableHead></TableRow></TableHeader><TableBody>{d.bysource.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.src}</TableCell><TableCell className={num()}>{scale(x.booked, f)}</TableCell><TableCell className={num()}>{scale(x.showed, f)}</TableCell><TableCell className={num()}>{x.rate}%</TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Show rate by source (%)"><BarH labels={d.bysource.map((x: any) => x.src)} data={d.bysource.map((x: any) => x.rate)} /></ChartCard></TabsContent>
      <TabsContent value="No-show Reasons"><Grid2><ChartCard title="No-show reasons"><Donut labels={d.reasons.labels} data={A(d.reasons.data, f)} /><DonutLegend labels={d.reasons.labels} data={A(d.reasons.data, f)} /></ChartCard><TableCard title="Breakdown"><Table><TableHeader><TableRow><TableHead>Reason</TableHead><TableHead className="text-right">Count</TableHead></TableRow></TableHeader><TableBody>{d.reasons.labels.map((l: string, i: number) => <TableRow key={i}><TableCell className="font-medium">{l}</TableCell><TableCell className={num()}>{scale(d.reasons.data[i], f)}</TableCell></TableRow>)}</TableBody></Table></TableCard></Grid2></TabsContent>
    </Tabs>
  );
}

/* ================= YoY Trading ================= */
export function YoyView({ d, f }: { d: any; f: number }) {
  const revBar = <GroupBar labels={d.months} groups={[{ name: "This year", data: A(d.rev.ty, f) }, { name: "Last year", data: A(d.rev.ly, f) }]} />;
  const yd = (ty: number, ly: number) => { const p = ((ty - ly) / ly) * 100; return <span className={p >= 0 ? "text-success" : "text-destructive"}>{p >= 0 ? "▲" : "▼"} {Math.abs(p).toFixed(1)}%</span>; };
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Revenue YoY", "Orders & AOV", "By Category"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Monthly revenue — this vs last year ($000s)" legend={["This year", "Last year"]}>{revBar}</ChartCard><ChartCard title="Revenue by category"><Donut labels={d.category.map((x: any) => x.cat)} data={A(d.category.map((x: any) => x.ty), f)} /><DonutLegend labels={d.category.map((x: any) => x.cat)} data={A(d.category.map((x: any) => x.ty), f)} money /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Revenue YoY" className="space-y-4"><ChartCard title="Monthly revenue — this vs last year ($000s)" legend={["This year", "Last year"]}>{revBar}</ChartCard><TableCard title="By month"><Table><TableHeader><TableRow><TableHead>Month</TableHead><TableHead className="text-right">This year</TableHead><TableHead className="text-right">Last year</TableHead><TableHead className="text-right">YoY</TableHead></TableRow></TableHeader><TableBody>{d.months.map((mo: string, i: number) => { const ty = d.rev.ty[i] * 1000 * f, ly = d.rev.ly[i] * 1000 * f; return <TableRow key={i}><TableCell className="font-medium">{mo}</TableCell><TableCell className={num()}>{money(ty)}</TableCell><TableCell className={num()}>{money(ly)}</TableCell><TableCell className={num()}>{yd(ty, ly)}</TableCell></TableRow>; })}</TableBody></Table></TableCard></TabsContent>
      <TabsContent value="Orders & AOV" className="space-y-4"><ChartCard title="Orders — this vs last year" legend={["This year", "Last year"]}><GroupBar labels={d.months} groups={[{ name: "This year", data: A(d.orders.ty, f) }, { name: "Last year", data: A(d.orders.ly, f) }]} /></ChartCard><TableCard title="By month"><Table><TableHeader><TableRow><TableHead>Month</TableHead><TableHead className="text-right">Orders TY</TableHead><TableHead className="text-right">Orders LY</TableHead><TableHead className="text-right">AOV TY</TableHead></TableRow></TableHeader><TableBody>{d.months.map((mo: string, i: number) => <TableRow key={i}><TableCell className="font-medium">{mo}</TableCell><TableCell className={num()}>{Math.round(d.orders.ty[i] * f)}</TableCell><TableCell className={num()}>{Math.round(d.orders.ly[i] * f)}</TableCell><TableCell className={num()}>{money(d.rev.ty[i] * 1000 / d.orders.ty[i])}</TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
      <TabsContent value="By Category" className="space-y-4"><ChartCard title="Revenue by category — this vs last year ($000s)" legend={["This year", "Last year"]}><GroupBar labels={d.category.map((x: any) => x.cat)} groups={[{ name: "This year", data: A(d.category.map((x: any) => x.ty / 1000), f) }, { name: "Last year", data: A(d.category.map((x: any) => x.ly / 1000), f) }]} /></ChartCard><TableCard title="Category"><Table><TableHeader><TableRow><TableHead>Category</TableHead><TableHead className="text-right">This year</TableHead><TableHead className="text-right">Last year</TableHead><TableHead className="text-right">YoY</TableHead></TableRow></TableHeader><TableBody>{d.category.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.cat}</TableCell><TableCell className={num()}>{money(x.ty * f)}</TableCell><TableCell className={num()}>{money(x.ly * f)}</TableCell><TableCell className={num()}>{yd(x.ty * f, x.ly * f)}</TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
    </Tabs>
  );
}

/* ================= Ecommerce ================= */
export function EcommerceView({ d, f }: { d: any; f: number }) {
  const total = d.channels.data.reduce((a: number, b: number) => a + b, 0);
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Sales", "Products", "Customers"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Sales over time" legend={["Gross", "Net"]}><TrendChart labels={AX} series={[{ name: "Gross", data: A(d.sales.gross, f) }, { name: "Net", data: A(d.sales.net, f) }]} /></ChartCard><ChartCard title="Sales by channel"><Donut labels={d.channels.labels} data={A(d.channels.data, f)} /><DonutLegend labels={d.channels.labels} data={A(d.channels.data, f)} money /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Sales" className="space-y-4"><ChartCard title="Sales over time" legend={["Gross", "Net"]}><TrendChart labels={AX} series={[{ name: "Gross", data: A(d.sales.gross, f) }, { name: "Net", data: A(d.sales.net, f) }]} height={320} /></ChartCard><TableCard title="Sales by channel"><Table><TableHeader><TableRow><TableHead>Channel</TableHead><TableHead className="text-right">Sales</TableHead><TableHead className="text-right">Share</TableHead></TableRow></TableHeader><TableBody>{d.channels.labels.map((l: string, i: number) => <TableRow key={i}><TableCell className="font-medium">{l}</TableCell><TableCell className={num()}>{money(scale(d.channels.data[i], f))}</TableCell><TableCell className={num()}>{Math.round(d.channels.data[i] / total * 100)}%</TableCell></TableRow>)}</TableBody></Table></TableCard></TabsContent>
      <TabsContent value="Products" className="space-y-4"><TableCard title="Top products"><Table><TableHeader><TableRow><TableHead>Product</TableHead><TableHead className="text-right">Units</TableHead><TableHead className="text-right">Revenue</TableHead><TableHead className="text-right">In stock</TableHead></TableRow></TableHeader><TableBody>{d.products.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.name}</TableCell><TableCell className={num()}>{scale(x.units, f)}</TableCell><TableCell className={num()}>{money(scale(x.revenue, f))}</TableCell><TableCell className={num()}>{x.stock}</TableCell></TableRow>)}</TableBody></Table></TableCard><ChartCard title="Revenue by product"><BarH labels={d.products.map((x: any) => x.name)} data={A(d.products.map((x: any) => x.revenue), f)} /></ChartCard></TabsContent>
      <TabsContent value="Customers"><Grid2><ChartCard title="New vs returning"><Donut labels={d.custMix.labels} data={A(d.custMix.data, f)} /><DonutLegend labels={d.custMix.labels} data={A(d.custMix.data, f)} /></ChartCard><TableCard title="Customer summary"><Table><TableHeader><TableRow><TableHead>Metric</TableHead><TableHead className="text-right">Value</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell className="font-medium">New customers</TableCell><TableCell className={num()}>{scale(1240, f)}</TableCell></TableRow><TableRow><TableCell className="font-medium">Returning</TableCell><TableCell className={num()}>{scale(606, f)}</TableCell></TableRow><TableRow><TableCell className="font-medium">Repeat rate</TableCell><TableCell className={num()}>33%</TableCell></TableRow></TableBody></Table></TableCard></Grid2></TabsContent>
    </Tabs>
  );
}

/* ================= Payments ================= */
export function PaymentsView({ d, f }: { d: any; f: number }) {
  return (
    <Tabs defaultValue="Overview" className="space-y-4"><Tl tabs={["Overview", "Payments", "Subscriptions", "Customers"]} />
      <TabsContent value="Overview" className="space-y-4"><KpiRow items={d.kpis} f={f} /><Grid2><ChartCard title="Payment volume" legend={["Gross", "Refunds"]}><TrendChart labels={AX} series={[{ name: "Gross", data: A(d.volume.gross, f) }, { name: "Refunds", data: A(d.volume.refunds, f) }]} dual /></ChartCard><ChartCard title="Successful vs failed"><Donut labels={d.successFail.labels} data={A(d.successFail.data, f)} /><DonutLegend labels={d.successFail.labels} data={A(d.successFail.data, f)} /></ChartCard></Grid2></TabsContent>
      <TabsContent value="Payments" className="space-y-4"><ChartCard title="Gross volume & refunds" legend={["Gross", "Refunds"]}><TrendChart labels={AX} series={[{ name: "Gross", data: A(d.volume.gross, f) }, { name: "Refunds", data: A(d.volume.refunds, f) }]} dual height={320} /></ChartCard><KpiRow items={pick(d.kpis, ["Gross Volume", "Net Revenue", "Successful", "Failed"])} f={f} /></TabsContent>
      <TabsContent value="Subscriptions" className="space-y-4"><ChartCard title="MRR & churned MRR" legend={["MRR", "Churned"]}><TrendChart labels={AX} series={[{ name: "MRR", data: A(d.mrr.mrr, f) }, { name: "Churned", data: A(d.mrr.churn, f) }]} dual height={320} /></ChartCard><KpiRow items={pick(d.kpis, ["MRR", "Churned MRR"])} f={f} /></TabsContent>
      <TabsContent value="Customers"><Grid2><ChartCard title="New customers by region"><BarH labels={d.geo.map((x: any) => x.r)} data={A(d.geo.map((x: any) => x.cust), f)} /></ChartCard><TableCard title="Regions"><Table><TableHeader><TableRow><TableHead>Region</TableHead><TableHead className="text-right">Customers</TableHead></TableRow></TableHeader><TableBody>{d.geo.map((x: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{x.r}</TableCell><TableCell className={num()}>{scale(x.cust, f)}</TableCell></TableRow>)}</TableBody></Table></TableCard></Grid2></TabsContent>
    </Tabs>
  );
}

/* ================= Reports ================= */
function ReportHeader({ icon, title, period, delivery }: { icon: string; title: string; period: string; delivery: string }) {
  return (
    <div className="flex items-center gap-4 rounded-xl bg-gradient-to-br from-primary via-violet-500 to-teal-400 p-5 text-white">
      <div className="grid h-11 w-11 place-items-center rounded-xl bg-white/20 text-xl">{icon}</div>
      <div><div className="text-lg font-bold">{title}</div><div className="text-xs opacity-90">{period}</div></div>
      <div className="ml-auto rounded-full bg-white/20 px-3 py-1 text-xs font-semibold">{delivery}</div>
    </div>
  );
}
function ReportBody({ f, insights }: { f: number; insights: string[] }) {
  const c = DATA.campaign;
  return (
    <>
      <KpiRow items={pick(c.kpis, ["Total Ad Spend", "Conversions", "Blended ROAS", "Attributed Revenue"])} f={f} />
      <ChartCard title="Spend & conversions" legend={["Spend", "Conv."]}><TrendChart labels={AX} series={[{ name: "Spend", data: A(c.trend.spend, f) }, { name: "Conv.", data: A(c.trend.conv, f) }]} dual /></ChartCard>
      <Card><CardHeader className="pb-2"><CardTitle className="text-[15px]">Insights &amp; actions</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{insights.map((x, i) => <div key={i} className="flex gap-2"><span className="text-primary">›</span><span dangerouslySetInnerHTML={{ __html: x }} /></div>)}</CardContent></Card>
    </>
  );
}
export function ReportsView({ d, f }: { d: any; f: number }) {
  return (
    <Tabs defaultValue="Weekly" className="space-y-4"><Tl tabs={["Weekly", "Monthly", "Quarterly", "KPI Scorecard"]} />
      <TabsContent value="Weekly" className="space-y-4"><ReportHeader icon={d.weekly.icon} title="Weekly Snapshot" period={d.weekly.period} delivery={d.weekly.delivery} /><ReportBody f={f} insights={["<b>ROAS up 9.6%</b> week-on-week — retargeting is carrying it.", "Meta leads softened mid-week; budget shifted to Google Brand.", "Action: scale Performance Max, pause Display remarketing."]} /></TabsContent>
      <TabsContent value="Monthly" className="space-y-4"><ReportHeader icon={d.monthly.icon} title="Monthly Performance" period={d.monthly.period} delivery={d.monthly.delivery} /><ReportBody f={f} insights={["<b>$177.6K revenue</b> at a <b>4.4x blended ROAS</b> — ahead of the 4.0x target.", "Google Ads efficiency improved (CPA −5.2%); Meta scaled reach +22%.", "Next month: test Advantage+ shopping, expand top lookalikes."]} /></TabsContent>
      <TabsContent value="Quarterly" className="space-y-4"><ReportHeader icon={d.quarterly.icon} title="Quarterly Business Review" period={d.quarterly.period} delivery={d.quarterly.delivery} /><ReportBody f={f} insights={["Quarter delivered <b>compounding growth</b> — revenue up across all three months.", "Web engagement rate held at 62% with rising organic share.", "Q3 focus: retention & LTV, creative refresh, GA4 conversion tracking."]} /></TabsContent>
      <TabsContent value="KPI Scorecard"><ReportHeader icon={d.kpi.icon} title="KPI Scorecard" period={d.kpi.period} delivery="Targets vs actuals" /><div className="mt-4"><TableCard title="Goals vs targets"><Table><TableHeader><TableRow><TableHead>KPI</TableHead><TableHead className="text-right">Actual</TableHead><TableHead className="text-right">Target</TableHead><TableHead>Progress</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{d.kpi.rows.map((r: any, i: number) => <TableRow key={i}><TableCell className="font-medium">{r.n}</TableCell><TableCell className={num()}>{r.a}</TableCell><TableCell className={num()}>{r.t}</TableCell><TableCell><div className="flex items-center gap-2"><div className="h-2 w-24 overflow-hidden rounded bg-muted"><div className="h-full rounded" style={{ width: r.pct + "%", background: r.s === "Achieved" ? "hsl(var(--success))" : r.s === "At risk" ? "hsl(var(--warning))" : "hsl(var(--primary))" }} /></div><span className="text-xs text-muted-foreground">{r.pct}%</span></div></TableCell><TableCell><Badge variant={r.s === "Achieved" ? "success" : r.s === "At risk" ? "warning" : "muted"}>{r.s}</Badge></TableCell></TableRow>)}</TableBody></Table></TableCard></div></TabsContent>
    </Tabs>
  );
}
