/* ============================================================
   seed-bq.mjs — turn the dashboard's demo data (src/data.ts) into
   BigQuery load files, isolated and tagged as DEMO so it can be
   dropped cleanly later.

   It does NOT touch BigQuery itself (no creds needed to run this).
   It writes, under .bq-demo/ :
     - one NDJSON file per client per mart table
     - JSON schemas for each table
     - load.sh — creates a demo_client_<slug> dataset per client
       (labeled env=demo) and bq-loads the NDJSON

   Push is a BigQuery LOAD JOB (bq load) — NOT Data Transfer Service.
   Run:  node scripts/seed-bq.mjs   (or: npm run seed:bq)
   Then: GCP_PROJECT=your-proj bash .bq-demo/load.sh
   ============================================================ */
import { build } from "esbuild";
import { mkdir, writeFile, chmod } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import path from "node:path";

const ROOT = process.cwd();
const OUT = path.join(ROOT, ".bq-demo");
const TMP = path.join(OUT, "_data.bundle.mjs");
const LOCATION = process.env.BQ_LOCATION || "australia-southeast1";
const SNAPSHOT = process.env.BQ_SNAPSHOT || "2026-07-31";
const TTL_DAYS = process.env.BQ_TTL_DAYS || ""; // e.g. "30" for auto-expiry; "" = none

/* Fixed, deterministic demo client set (slug + demo scale factor). */
const DEMO_CLIENTS = [
  { slug: "aqua-pulse-spas", f: 1 },
  { slug: "care-for-you-at-home", f: 0.42 },
  { slug: "ms-plus", f: 1.8 },
];
const datasetOf = (slug) => "demo_client_" + slug.replace(/-/g, "_"); // BQ dataset ids: no hyphens
const scale = (v, f, rate) => (rate ? v : Math.round(v * f));

/* --- bundle src/data.ts so we can import the DATA object (type-only @ imports are erased) --- */
await mkdir(OUT, { recursive: true });
await build({ entryPoints: ["src/data.ts"], bundle: true, format: "esm", outfile: TMP, logLevel: "silent" });
const { DATA } = await import(pathToFileURL(TMP).href + "?t=" + Date.now());

/* --- flatten to rows --- */
const kpiRows = {};   // dataset -> rows
const pathRows = {};  // dataset -> rows
for (const c of DEMO_CLIENTS) {
  const ds = datasetOf(c.slug);
  kpiRows[ds] = [];
  pathRows[ds] = [];
  for (const [mod, d] of Object.entries(DATA)) {
    if (Array.isArray(d?.kpis)) {
      d.kpis.forEach((k, ord) => {
        kpiRows[ds].push({
          client_id: c.slug, module: mod, ord,
          label: k.l,
          value: String(typeof k.v === "number" ? scale(k.v, c.f, k.rate) : k.v),
          fmt: k.fmt ?? null, delta: k.d ?? null, dir: k.dir ?? null,
          good: k.good ?? null, rate: !!k.rate, hero: !!k.hero,
          is_demo: true, snapshot_date: SNAPSHOT,
        });
      });
    }
    if (mod === "attribution" && Array.isArray(d?.paths)) {
      d.paths.forEach((p, ord) => {
        pathRows[ds].push({
          client_id: c.slug, ord, path: p.path,
          conv: Math.round(p.conv * c.f), rev: Math.round(p.rev * c.f),
          is_demo: true, snapshot_date: SNAPSHOT,
        });
      });
    }
  }
}

/* --- schemas (explicit; path is a REPEATED STRING = ARRAY<STRING>) --- */
const SCHEMAS = {
  marts_kpis: [
    { name: "client_id", type: "STRING" }, { name: "module", type: "STRING" }, { name: "ord", type: "INT64" },
    { name: "label", type: "STRING" }, { name: "value", type: "STRING" }, { name: "fmt", type: "STRING" },
    { name: "delta", type: "FLOAT64" }, { name: "dir", type: "STRING" }, { name: "good", type: "STRING" },
    { name: "rate", type: "BOOL" }, { name: "hero", type: "BOOL" },
    { name: "is_demo", type: "BOOL" }, { name: "snapshot_date", type: "DATE" },
  ],
  marts_attribution_paths: [
    { name: "client_id", type: "STRING" }, { name: "ord", type: "INT64" },
    { name: "path", type: "STRING", mode: "REPEATED" },
    { name: "conv", type: "INT64" }, { name: "rev", type: "INT64" },
    { name: "is_demo", type: "BOOL" }, { name: "snapshot_date", type: "DATE" },
  ],
};

/* --- write NDJSON + schema files --- */
const schemaDir = path.join(OUT, "schema");
await mkdir(schemaDir, { recursive: true });
for (const [table, schema] of Object.entries(SCHEMAS)) {
  await writeFile(path.join(schemaDir, `${table}.json`), JSON.stringify(schema, null, 2) + "\n");
}
const ndjson = (rows) => rows.map((r) => JSON.stringify(r)).join("\n") + "\n";
for (const c of DEMO_CLIENTS) {
  const ds = datasetOf(c.slug);
  const dir = path.join(OUT, ds);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "marts_kpis.ndjson"), ndjson(kpiRows[ds]));
  await writeFile(path.join(dir, "marts_attribution_paths.ndjson"), ndjson(pathRows[ds]));
}

/* --- generate load.sh (create labeled datasets + bq load) --- */
const expiryFlag = TTL_DAYS ? ` --default_table_expiration ${Number(TTL_DAYS) * 86400}` : "";
let sh = `#!/usr/bin/env bash
# Generated by scripts/seed-bq.mjs — loads the DEMO data into BigQuery.
# Prereqs: gcloud auth (a service account with BigQuery Data Editor + Job User), and:
#   export GCP_PROJECT=your-project-id
set -euo pipefail
: "\${GCP_PROJECT:?set GCP_PROJECT to your GCP project id}"
LOCATION="${LOCATION}"
echo "Loading Entangle DEMO data into $GCP_PROJECT ($LOCATION)"
`;
for (const c of DEMO_CLIENTS) {
  const ds = datasetOf(c.slug);
  sh += `
# ---- ${c.slug} ----
bq --location="$LOCATION" mk --dataset --force${expiryFlag} \\
  --label env:demo --description "Entangle DEMO data (removable) — ${c.slug}" \\
  "$GCP_PROJECT:${ds}"
bq --location="$LOCATION" load --replace --source_format=NEWLINE_DELIMITED_JSON \\
  "$GCP_PROJECT:${ds}.marts_kpis" ".bq-demo/${ds}/marts_kpis.ndjson" ".bq-demo/schema/marts_kpis.json"
bq --location="$LOCATION" load --replace --source_format=NEWLINE_DELIMITED_JSON \\
  "$GCP_PROJECT:${ds}.marts_attribution_paths" ".bq-demo/${ds}/marts_attribution_paths.ndjson" ".bq-demo/schema/marts_attribution_paths.json"
`;
}
sh += `
echo "Done. Verify:  bq query --use_legacy_sql=false 'SELECT module, COUNT(*) FROM \\\`${datasetOf(DEMO_CLIENTS[0].slug)}.marts_kpis\\\` GROUP BY module'"
`;
const loadPath = path.join(OUT, "load.sh");
await writeFile(loadPath, sh);
await chmod(loadPath, 0o755);

const totalKpis = Object.values(kpiRows).reduce((n, r) => n + r.length, 0);
const totalPaths = Object.values(pathRows).reduce((n, r) => n + r.length, 0);
console.log(`✓ Wrote demo load files to .bq-demo/`);
console.log(`  clients: ${DEMO_CLIENTS.length} · datasets: ${DEMO_CLIENTS.map((c) => datasetOf(c.slug)).join(", ")}`);
console.log(`  rows: ${totalKpis} KPI rows, ${totalPaths} attribution-path rows (all tagged is_demo=true)`);
console.log(`\nNext:\n  export GCP_PROJECT=your-project-id\n  bash .bq-demo/load.sh`);
